config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root to: "pages#home"

  resources :artists
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  validates :name, presence: true, length: { minimum: 2 }

  has_many :songs, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
has_and_belongs_to_many :songs

validates :name, presence: true, length: { minimum: 2 }

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_and_belongs_to_many :genres

  validates :title, :genre, presence: true
  validates :artwork_url, length: { maximum: 255 }, allow_blank: true


  def self.order_by_name
    order(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render "new"
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update_attributes(artist_params)
      redirect_to @artist
    else
      render "edit"
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end


  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to @genre
    else
      render "new"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update_attributes(genre_params)
      redirect_to @genre
    else
      render "edit"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render "new"
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    if @song.update_attributes(song_params)
      redirect_to @song
    else
      render "edit"
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :release_year, :genre, :artwork_url, :album, :artist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

  <ul>
    <% @artist.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>


<div class="form-group">
  <label>Name</label>
  <%= f.text_field :name, placeholder: "Artist Name", class: "form-control" %>
</div>

<%= f.submit (@artist.new_record? ? "Create" : "Update"), class: "btn btn-default" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

<button class="btn btn-default">
  <%= link_to "Add new Artist", new_artist_path %>

</button>

app/views/artists/new.html.erb
<h1>Add a new Artist</h1>

<%= render "form" %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @artist.name %></h3>


<h6>List of Songs</h6>
<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
     <li class="song-title"><%= song.title %></li>
     <% end %>
  </ul>
<% else %>
  <p>This artist does not have any songs yet.. </p>
<% end %>


<button class="btn btn-default">
  <%= link_to "Edit Artist", edit_artist_path(@artist.id) %>
</button>

<button class="btn btn-default">
  <%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: {  confirm: "Are you sure you want to delete this artist?" } %>
</button>

<button class="btn btn-default">
  <%= link_to "All Artists", artists_path %>
</button>

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>

  <ul>
    <% @genre.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>


<div class="form-group">
  <label>Name</label>
  <%= f.text_field :name, placeholder: "Genre Name", class: "form-control" %>
</div>

<%= f.submit (@genre.new_record? ? "Create" : "Update"), class: "btn btn-default" %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render "form" %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<% @genres.each do |genre| %>
  <p><%= link_to genre.name, genre_path(genre.id) %></p>
<% end %>

<button class="btn btn-default">
  <%= link_to "Add new Genre", new_genre_path %>

</button>

app/views/genres/new.html.erb
<h1>Add a new Genre</h1>

<%= render "form" %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @genre.name %></h3>


<button class="btn btn-default">
  <%= link_to "Edit Genre", edit_genre_path(@genre.id) %>
</button>

<button class="btn btn-default">
  <%= link_to "Delete Genre", genre_path(@genre.id), method: :delete, data: {  confirm: "Are you sure you want to delete this genre?" } %>
</button>

<button class="btn btn-default">
  <%= link_to "All Genres", genres_path %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  </head>

  <body>

    <%= render "shared/navbar" %>



    <div class="container">
      <%= yield %>
    </div>
    <br><br>

    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<!-- HEADER -->
<header>

  <div>
    <h1>Welcome to <img src="<%= asset_path( 'Codaisseurify_Logo2.png', class: "logo" ) %>" /></h1>
    <h3><strong>real</strong> music for <strong>real</strong> devs</h3>
  </div>


</header>

app/views/shared/_footer.html.erb
<footer class="container-fluid">
			<p>Designed, written and coded by <a href="https://github.com/ipresilia"
        class="footer-link" target="_blank">Ilsmarie Presilia</a></p>
</footer>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

<!-- LOGO!!! -->
        <div class="logo">
         <%= link_to root_path do %>
          <img src="<%= asset_path( 'Codaisseurify_Logo.png', class: "logo" ) %>" />
         <% end%>
       </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "Artists", artists_path %></li>
          <li><%=link_to "Genres", genres_path %></li>
          <li><%=link_to "Songs", songs_path %></li>
      </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>

  <ul>
    <% @song.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>


<div class="form-group">
  <label>Title</label>
  <%= f.text_field :title, placeholder: "Song Title", class: "form-control" %>
</div>

<div class="form-group">
  <label>Release year</label><br>
  <%= f.select :release_year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1), prompt: "Select a year", class: "form-control" %>
</div>

<div class="form-group">
  <label>Genre</label>
  <%= f.text_field :genre, placeholder: "Song Genre", class: "form-control" %>
</div>

<div class="form-group">
  <label>Artwork</label>
  <%= f.text_field :artwork_url, placeholder: "Song Artwork", class: "form-control" %>
</div>

<div class="form-group">
  <label>Album</label>
  <%= f.text_field :album, placeholder: "Song Album", class: "form-control" %>
</div>

<div class="form-group">
  <label>Artist</label><br>
  <!-- <%= f.collection_select(:artist_id, Artist.all, :id, :name)%> -->
  <%= f.text_field :artist, placeholder: "Artist", class: "form-control" %>
</div>



  <%= f.submit (@song.new_record? ? "Create" : "Update"), class: "btn btn-default" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
  <p><%= link_to song.title, song_path(song.id) %></p>
<% end %>

<button class="btn btn-default">
  <%= link_to "Add new Song", new_song_path %>

</button>

app/views/songs/new.html.erb
<h1>Add a new Song</h1>

<%= render "form" %>

<!-- <%= form_for @song do |f| %>

<div class="form-group">
  <label>Title</label>
  <%= f.text_field :title, placeholder: "Song Title", class: "form-control" %>
</div>

<div class="form-group">
  <label>Release year</label>
  <%= f.select :release_year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1), prompt: "Select a year", class: "form-control" %>
</div>

<div class="form-group">
  <label>Genre</label>
  <%= f.text_field :genre, placeholder: "Song Genre", class: "form-control" %>
</div>

<div class="form-group">
  <label>Artwork</label>
  <%= f.text_field :artwork_url, placeholder: "Song Artwork", class: "form-control" %>
</div>

<div class="form-group">
  <label>Album</label>
  <%= f.text_field :album, placeholder: "Song Album", class: "form-control" %>
</div>

  <%= f.submit "Create", class: "btn btn-default" %>
<% end %> -->

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<p>Release Year: <%= @song.release_year %></p>
<p>Genre: <%= @song.genre %></p>
<p>Album: <%= @song.album %></p>
<p>Artist: <%= @song.artist %></p>
<%= image_tag @song.artwork_url %>
<br>
<br>

<button class="btn btn-default">
  <%= link_to "Edit Song", edit_song_path(@song.id) %>
</button>

<button class="btn btn-default">
  <%= link_to "Delete Song", song_path(@song.id), method: :delete, data: {  confirm: "Are you sure you want to delete this song?" } %>
</button>

<button class="btn btn-default">
  <%= link_to "All Songs", songs_path %>
</button>